### ISSUE TITLE
Github Pages build fails with the new hacker style changes

### ISSUE THREAD

**Issue by kishorbhat** [b2a3e8/jekyll-theme-console#20]
Hi! Thanks for putting in the work for your theme, I love it.

The recent hacker style changes don't sit well with Github Pages - I'm seeing the following error on build:

`Your SCSS file assets/main-hacker.scss has an error on line 16: Undefined variable: "$background-color".`

Local build works perfectly fine.

Here's a [link](https://github.com/kishorbhat/kishorbhat.github.io/runs/829568641) to the run page, but it doesn't have much more info. I'm pulling in the theme using `remote_theme` in `_config.yml`.

**Comment by b2a3e8** [comment]
Hi! Thanks for reporting! I’ll look into this tomorrow.

**Comment by b2a3e8** [comment]
Issue is solved in v0.3.9. Can you confirm that?

**Comment by kishorbhat** [comment]
Build still fails, here's the run: https://github.com/kishorbhat/kishorbhat.github.io/runs/836367535.

**Comment by b2a3e8** [comment]
Ok so I troubleshooted again and now found the real problem. In your repo you have `_sass/base.scss`, `_sass/dark.scss`, `_sass/light.scss`, `assets/main-dark.scss` and `assets/main-light.scss` files. After I deleted them in my fork, everything worked.
So what do you need those files for?

**Comment by kishorbhat** [comment]
... huh. You're right; I'd cloned the theme repo to use the "source code as a template for an easy start" like you mentioned in your README, and didn't think too much of it later. I removed the files and the gh-pages build works; see https://github.com/kishorbhat/kishorbhat.github.io/runs/837027337.

That said, I'll still need those files for local testing, so I'll probably add them to my `.gitignore` for now.

Thanks a bunch for troubleshooting! I'll close this one out now. :)
